#!/bin/sh

echo "Select program"
echo;
echo "1. Rename / rename and numerically order filenames: *.mrc -> ####_Nametag.mrcs"
echo;
echo "2. OpticsGroupName / add OpticsGroupName in *.star files"
echo;

printf "Select : "
read prgm

case "$prgm" in

#///////////////////////////////////////////// Rename ////////////////////////////////////////////////////////

	"1") 



echo;
echo "-----------------------------------------------------"
echo "|                    Rename mrcs                    |"
echo "-----------------------------------------------------"
echo "Last updated: 2020/04/07"
echo "* means any filename, ##### means ordered filenames -> expected output is 00001.mrc, 00002.mrc, ......"
echo "Nametag input sample(KARA) -> expected output(00001_KARA.mrc)"
echo;

echo "1. *.mrc  ----->  #####_Nametag.mrc"
echo;
echo "2. *.mrc  ----->  #####_Nametag.mrcs"
echo;
echo "3. *.mrcs ----->  #####_Nametag.mrcs"
echo;
echo "4. *.tiff ----->  #####_Nametag.tiff"
echo;

printf "Select : "
read Selection

printf "Nametag : "
read Nametag

a=1

case "$Selection" in

	"1")

	printf "Your selection is *.mrc  ----->  #####_%s.mrc / IS IT CORRECT? (y/n)" "$Nametag"
	read correct
	if [ $correct=="y" ]
	then
		for i in *.mrc; do

        		new=$(printf "%05d_%s.mrc" "$a" "$Nametag")
    			mv -- "$i" "$new"
        		let a=a+1

		done
	fi
	;;


	"2")

        printf "Your selection is *.mrc  ----->  #####_%s.mrcs / IS IT CORRECT? (y/n)" "$Nametag"
        read correct
        if [ $correct=="y" ]
	then

                for i in *.mrc; do

                        new=$(printf "%05d_%s.mrcs" "$a" "$Nametag")
                        mv -- "$i" "$new"
                        let a=a+1

                done
        
	fi
        ;;

	"3")

        printf "Your selection is *.mrcs  ----->  #####_%s.mrcs / IS IT CORRECT? (y/n)" "$Nametag"
        read correct
        if [ $correct=="y" ]
	then
                for i in *.mrcs; do

                        new=$(printf "%05d_%s.mrcs" "$a" "$Nametag")
                        mv -- "$i" "$new"
                        let a=a+1

                done
	
        fi
        ;;

	"4")
 
         printf "Your selection is *.tiff  ----->  #####_%s.tiff / IS IT CORRECT? (y/n)" "$Nametag"
         read correct
         if [ $correct=="y" ]
     then
                 for i in *.tiff; do
 
                         new=$(printf "%05d_%s.tiff" "$a" "$Nametag")
                         mv -- "$i" "$new"
                         let a=a+1
 
                 done
 
         fi
         ;;

	*) exit 0
esac


;;

#///////////////////////////////// End of Rename ///////////////////////////////////////////////


#//////////////////////////////// OpticsGroupName //////////////////////////////////////////////////

	"2")

echo;
echo "-----------------------------------------------------"
echo "|               Insert OpticsGroupName              |"
echo "-----------------------------------------------------"
echo "Last updated: 2020/09/04"
echo;

echo "*.star file location: "
read starloc
echo;

echo "Insert OpticsGroupName from line: "
read linestart
echo;

echo "Value for the OpticsGroupName is: "
read opticsgroup
echo;

echo;
echo "*.star file locatation: $starloc"
echo "Insert OpticsGroupName of $opticsgroup from line $linestart"
echo;
echo "IS IT CORRECT? (y/n)"
read correct

	if [ $correct=="y" ]
   	then

	echo;

	(vim -c "$linestart,$ s/^/$opticsgroup " -c wq $starloc)
	
	echo "Don't forget to add \"_rlnOpticsGroupName #1\" before \"_rlnImageName\" in your *.star file!"

	fi


;;

	*) exit 0

esac

echo "Complete."

exit 0
